language: ruby
rvm:
- 2.3.1
sudo: required
services:
- postgresql
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- gpg --passphrase "$KEY" --output config/application.yml --decrypt config/application.yml.asc
- psql -c 'create database redeemify_test;' -U postgres
- gem install bundler
- gem install rake
- bundle exec rake db:create:all
- bundle exec rake db:migrate
deploy:
  provider: heroku
  app:
    master: redeemify-staging
  run: rake db:migrate
  api_key:
    secure: Xh+4efJXCkz/OtmtdkerQhaj9PTrUtclSCvT7hTOhRTd8fI/4q6LDl6FJQK1IhXnO7XJDqtWiXvKr74R/j3DelYDqAUDzuLteoNot2ZRyiq05nPX27morfxrfyKZX0PglpBSkwUPPgJxq22wtcfUlvW6XzvoxMk9xGkr/jsOjGV82hcBY4nvHnfGCyNRn0ZMTk8lItDKYHSValYP2Yi7AsPFpXDn+ag9vPNsQUzqerKCzX6+yXxlUiocxiaDLn71IRC35sD445yqjYC7tx+5MzY1u1ud5H78p/FlOCv09XDnrpYt6mdzKum9/uBX47B7lvL8Vs9cUQD8qS3Mg6lsFs0vgRDLwokRD51j2zLojJ87gxavLqxAJmPG2igHmahHeowj7ZyoYE4hLCJdrTSs1xvMS4MOUtI1mp65FxE/BVSdkP5Rye+PXBHQuAlPucxFQf2/hoJ3RtX1YgVDKWelotEM4u/baYLjGmsXS9OGzkc5LTollYI7TRfb3woSttrcPchTQM6K0DkA3KdWwDFwUjOLm5MnAjxLAWfLPahN8NdcOwP9lQdj5tiJYWuPus3qBAuY0TsP9tWYELbAS1HfR25eZj3zGlh7KNdevz4RvLQdjqrDxOuZ1XmCXFQ2GClz3A+PbcEVLKMPNAXF3Le6M0y+3vmr3/3lSVsQBIKt3/w=
